# Generated by Django 5.1.4 on 2026-01-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='notebooks.knowledgespace'),
        ),
        migrations.AddField(
            model_name='document',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='notebooks.knowledgespace'),
        ),
    ]
