from django.conf import settings
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives


def send_contact_email_to_company(data):
    subject = f"📩 New Contact Message — {data['subject']}"
    html_content = f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; background-color: #fff; color: #111; border: 1px solid #ddd; border-radius: 8px; padding: 24px; max-width: 600px; margin: auto;">
        <h2 style="border-bottom: 2px solid #000; padding-bottom: 8px;">New Contact Submission</h2>
        <p style="font-size: 15px;">You’ve received a new message through the contact form:</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
            <tr><td style="padding: 8px 0;"><strong>Name:</strong></td><td>{data['name']}</td></tr>
            <tr><td style="padding: 8px 0;"><strong>Email:</strong></td><td>{data['email']}</td></tr>
            <tr><td style="padding: 8px 0;"><strong>Phone:</strong></td><td>{data.get('phone') or 'N/A'}</td></tr>
            <tr><td style="padding: 8px 0;"><strong>Subject:</strong></td><td>{data['subject']}</td></tr>
        </table>
        <div style="margin-top: 20px; padding: 16px; background-color: #f9f9f9; border-left: 4px solid #000;">
            <p style="margin: 0;"><strong>Message:</strong></p>
            <p style="margin-top: 6px; white-space: pre-line;">{data['message'].replace('\n', '<br>')}</p>
        </div>
        <p style="margin-top: 32px; font-size: 13px; color: #666;">This message was automatically generated by the StudyMate contact API.</p>
    </div>
    """
    text_content = strip_tags(html_content)

    email = EmailMultiAlternatives(
        subject=subject,
        body=text_content,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[settings.CONTACT_NOTIFICATION_EMAIL],
    )
    email.attach_alternative(html_content, "text/html")
    email.send(fail_silently=False)


def send_contact_email_to_client(data):
    subject = "🤍 Thank You for Contacting Us!"
    html_content = f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; background-color: #fff; color: #111; border: 1px solid #ddd; border-radius: 8px; padding: 24px; max-width: 600px; margin: auto;">
        <h2 style="text-align: center; border-bottom: 2px solid #000; padding-bottom: 8px;">Thank You, {data['name']}!</h2>
        <p style="font-size: 15px; line-height: 1.6;">We’ve received your message and our team will get back to you shortly.</p>
        <div style="margin-top: 20px; padding: 16px; background-color: #f9f9f9; border-left: 4px solid #000;">
            <p style="margin: 0;"><strong>Your message:</strong></p>
            <p style="margin-top: 6px; white-space: pre-line;">{data['message'].replace('\n', '<br>')}</p>
        </div>
        <p style="margin-top: 24px; line-height: 1.5;">
            Warm regards,<br>
            <strong>The StudyMate Team</strong><br>
            <span style="font-size: 13px; color: #777;">AI-Powered Learning. Human-Centered Design.</span>
        </p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
        <p style="font-size: 12px; text-align: center; color: #999;">This is an automated email — please don’t reply directly.</p>
    </div>
    """
    text_content = strip_tags(html_content)

    email = EmailMultiAlternatives(
        subject=subject,
        body=text_content,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[data["email"]],
    )
    email.attach_alternative(html_content, "text/html")
    email.send(fail_silently=False)
